import type { ActionCard, BuffState, EventSpec, ModelSpec, ProjectSpec } from './types'

export const PRICE_SNAPSHOT = '2026-09-10'
export const USD_CNY_REFERENCE = 7.15

export const PRICE_NOTE = `外币模型按 1 USD ≈ ¥${USD_CNY_REFERENCE.toFixed(2)} 的游戏参考汇率换算。价格为 ${PRICE_SNAPSHOT} 官方公开价快照，不代表实时账单。`

export const MODELS: ModelSpec[] = [
  {
    id: 'codax-luna',
    parodyName: 'GBT-5.6 Luna',
    realName: 'GPT-5.6 Luna',
    provider: 'OpenAI',
    ratesCny: { input: 1.43, cached: 0.143, output: 8.58 },
    nativePrice: '$0.20 / $0.02 / $1.20',
    contextLabel: 'Codax 工作区配额',
    power: 0.82,
    reliability: 0.72,
    speed: 1.25,
    reasoning: 0.72,
    contextEfficiency: 1.08,
    workflowDiscipline: 0.62,
    failureRecovery: 0.55,
    trait: '便宜快 · 需要你盯流程',
    color: '#77e6b6',
    sourceUrl: 'https://help.openai.com/en/articles/20001415',
    sourceLabel: 'OpenAI Token Rate Card',
    note: '输入 / 缓存输入 / 输出，每百万 Token。',
  },
  {
    id: 'deep-flash',
    parodyName: 'DeepSick Flash',
    realName: 'DeepSeek-V4.1-Flash',
    provider: 'DeepSeek',
    ratesCny: { input: 2.145, cached: 0.0429, output: 8.58 },
    nativePrice: '$0.30 / $0.006 / $1.20（高峰）',
    contextLabel: '1M',
    power: 0.9,
    reliability: 0.76,
    speed: 1.2,
    reasoning: 0.82,
    contextEfficiency: 0.96,
    workflowDiscipline: 0.76,
    failureRecovery: 0.62,
    trait: '缓存友好 · 擅长快速试错',
    color: '#64a8ff',
    sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing/',
    sourceLabel: 'DeepSeek Models & Pricing',
    note: '采用工作日高峰价；“错峰运行”Buff 按官方低谷价减半。',
  },
  {
    id: 'glm-flash',
    parodyName: 'Gloom 5.3 Flash',
    realName: 'GLM-5.3-Flash',
    provider: '智谱 AI',
    ratesCny: { input: 0.8, cached: 0.23, output: 2.8 },
    nativePrice: '¥0.80 / ¥0.23 / ¥2.80',
    contextLabel: '1M',
    power: 0.84,
    reliability: 0.73,
    speed: 1.35,
    reasoning: 0.78,
    contextEfficiency: 1.02,
    workflowDiscipline: 0.7,
    failureRecovery: 0.58,
    trait: '速度极快 · 复杂任务会飘',
    color: '#ff8cc8',
    sourceUrl: 'https://docs.bigmodel.cn/cn/guide/start/pricing',
    sourceLabel: '智谱 API 定价',
    note: '输入 / 缓存命中 / 输出，每百万 Token。',
  },
  {
    id: 'gemina-flash',
    parodyName: 'Gemina 3.8 Flash',
    realName: 'Gemini 3.8 Flash',
    provider: 'Google',
    ratesCny: { input: 5.3625, cached: 0.53625, output: 26.8125 },
    nativePrice: '$0.75 / $0.075 / $3.75（推广期）',
    contextLabel: '1M 级',
    power: 1.0,
    reliability: 0.8,
    speed: 1.3,
    reasoning: 0.96,
    contextEfficiency: 0.84,
    workflowDiscipline: 0.86,
    failureRecovery: 0.72,
    trait: '长上下文 · 中高难度均衡',
    color: '#b596ff',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
    sourceLabel: 'Gemini Developer API Pricing',
    note: '采用截至 2026-12-31 的推广价。',
  },
  {
    id: 'qwan-max',
    parodyName: 'Qwan 3.8 Max',
    realName: 'qwen3.8-max',
    provider: '阿里云百炼',
    ratesCny: { input: 12, cached: 1.2, output: 36 },
    nativePrice: '¥12.00 / 约¥1.20 / ¥36.00',
    contextLabel: '1M',
    power: 1.12,
    reliability: 0.85,
    speed: 1.0,
    reasoning: 1.08,
    contextEfficiency: 0.78,
    workflowDiscipline: 0.9,
    failureRecovery: 0.8,
    trait: '强推理 · 贵，但不怕大活',
    color: '#ffbd66',
    sourceUrl: 'https://help.aliyun.com/zh/model-studio/model-pricing',
    sourceLabel: '阿里云百炼模型价格',
    note: '北京地域原价；缓存价按官方命中约为标准输入 10% 的规则推算。',
  },
  {
    id: 'cloude-sonnet',
    parodyName: 'Cloude Sonnet 5',
    realName: 'Claude Sonnet 5',
    provider: 'Anthropic',
    ratesCny: { input: 14.3, cached: 1.43, output: 71.5 },
    nativePrice: '$2.00 / $0.20 / $10.00',
    contextLabel: '长上下文',
    power: 1.2,
    reliability: 0.9,
    speed: 0.95,
    reasoning: 1.14,
    contextEfficiency: 0.7,
    workflowDiscipline: 0.96,
    failureRecovery: 0.86,
    trait: '稳健审慎 · 最会收拾残局',
    color: '#ff956f',
    sourceUrl: 'https://platform.claude.com/docs/en/about-claude/pricing',
    sourceLabel: 'Claude Platform Pricing',
    note: '输入 / 缓存命中 / 输出，每百万 Token。',
  },
  {
    id: 'glm-5.3',
    parodyName: 'Gloom 5.3',
    realName: 'GLM-5.3',
    provider: '智谱 AI',
    ratesCny: { input: 8, cached: 2, output: 28 },
    nativePrice: '¥8.00 / ¥2.00 / ¥28.00',
    contextLabel: '1M',
    power: 1.18,
    reliability: 0.88,
    speed: 0.98,
    reasoning: 1.12,
    contextEfficiency: 0.72,
    workflowDiscipline: 0.93,
    failureRecovery: 0.84,
    trait: '中文项目强 · 证据链完整',
    color: '#ff72ad',
    sourceUrl: 'https://docs.bigmodel.cn/cn/guide/start/pricing',
    sourceLabel: '智谱 API 定价',
    note: '输入 / 缓存命中 / 输出，每百万 Token。',
  },
  {
    id: 'codax-terra',
    parodyName: 'GBT-5.6 Terra',
    realName: 'GPT-5.6 Terra',
    provider: 'OpenAI',
    ratesCny: { input: 14.3, cached: 1.43, output: 85.8 },
    nativePrice: '$2.00 / $0.20 / $12.00',
    contextLabel: 'Codax 工作区配额',
    power: 1.25,
    reliability: 0.91,
    speed: 0.92,
    reasoning: 1.22,
    contextEfficiency: 0.64,
    workflowDiscipline: 1.0,
    failureRecovery: 0.91,
    trait: '高能力 · 少读几遍上下文',
    color: '#4be0a0',
    sourceUrl: 'https://help.openai.com/en/articles/20001415',
    sourceLabel: 'OpenAI Token Rate Card',
    note: '输入 / 缓存输入 / 输出，每百万 Token。',
  },
  {
    id: 'codax-sol',
    parodyName: 'GBT-5.6 Sol',
    realName: 'GPT-5.6 Sol',
    provider: 'OpenAI',
    ratesCny: { input: 28.6, cached: 2.86, output: 143 },
    nativePrice: '$4.00 / $0.40 / $20.00',
    contextLabel: 'Codax 工作区配额',
    power: 1.42,
    reliability: 0.95,
    speed: 0.82,
    reasoning: 1.34,
    contextEfficiency: 0.54,
    workflowDiscipline: 1.08,
    failureRecovery: 0.97,
    trait: '终局大杀器 · 贵且慢',
    color: '#31d38a',
    sourceUrl: 'https://help.openai.com/en/articles/20001415',
    sourceLabel: 'OpenAI Token Rate Card',
    note: '输入 / 缓存输入 / 输出，每百万 Token。',
  },
]

export const STARTER_MODEL_IDS = ['codax-luna', 'deep-flash', 'glm-flash']

export const ACTION_CARDS: ActionCard[] = [
  {
    id: 'scan-repo',
    name: '扫描仓库',
    command: '/inspect --tree',
    description: '读取文件树与关键入口，建立最小心智模型。',
    kind: 'inspect',
    risk: '低',
    inputRange: [2400000, 5800000],
    outputRange: [180000, 480000],
    timeCost: 1,
    cooldown: 1,
    contextLoad: 0.44,
    effect: { analysis: 2, stability: 1 },
    workflowStage: '调查',
    sequenceTip: '先建立文件地图',
  },
  {
    id: 'read-logs',
    name: '追踪日志',
    command: '/trace --errors',
    description: '沿堆栈寻找真正的爆点，可能揭露隐藏风险。',
    kind: 'inspect',
    risk: '低',
    inputRange: [2000000, 5000000],
    outputRange: [260000, 680000],
    timeCost: 1,
    cooldown: 1,
    contextLoad: 0.38,
    effect: { analysis: 2, review: 1 },
    requires: { analysis: 1 },
    workflowStage: '调查',
    sequenceTip: '先扫描，再追踪爆点',
  },
  {
    id: 'ask-plan',
    name: '先写计划',
    command: '/plan --before-code',
    description: '先规划再动手，慢一点，但能降低大型修改的翻车率。',
    kind: 'inspect',
    risk: '低',
    inputRange: [3200000, 7500000],
    outputRange: [420000, 1100000],
    timeCost: 1,
    cooldown: 2,
    contextLoad: 0.46,
    effect: { analysis: 1, code: 1, review: 1 },
    requires: { analysis: 1 },
    workflowStage: '计划',
    sequenceTip: '有证据后再写计划',
  },
  {
    id: 'precision-patch',
    name: '精准补丁',
    command: '/edit --minimal',
    description: '修改最少的代码；调查充分时非常可靠。',
    kind: 'build',
    risk: '中',
    inputRange: [6500000, 16000000],
    outputRange: [650000, 1800000],
    timeCost: 2,
    cooldown: 1,
    contextLoad: 0.52,
    effect: { code: 3 },
    requires: { analysis: 2 },
    workflowStage: '实现',
    sequenceTip: '至少完成一次调查',
  },
  {
    id: 'rewrite-module',
    name: '整段重写',
    command: '/rewrite --yolo',
    description: '进度很快，也可能把一个 Bug 升级为一个功能。',
    kind: 'build',
    risk: '高',
    inputRange: [14000000, 34000000],
    outputRange: [1800000, 4800000],
    timeCost: 2,
    cooldown: 2,
    contextLoad: 0.62,
    effect: { code: 5, stability: -7 },
    requires: { analysis: 2, reviews: 1 },
    workflowStage: '实现',
    sequenceTip: '没有评审就别按 YOLO',
  },
  {
    id: 'manual-hotfix',
    name: '人工热修',
    command: 'vim fix.ts',
    description: '不用 Token，但要消耗珍贵的程序员时间。',
    kind: 'build',
    risk: '中',
    inputRange: [0, 0],
    outputRange: [0, 0],
    timeCost: 3,
    cooldown: 2,
    contextLoad: 0,
    effect: { code: 2, stability: 2 },
    requires: { analysis: 1 },
    workflowStage: '实现',
    sequenceTip: '先看一眼现场再改',
    manual: true,
  },
  {
    id: 'unit-tests',
    name: '跑针对性测试',
    command: 'npm test -- related',
    description: '便宜地验证关键路径，顺便戳穿一句“应该好了”。',
    kind: 'verify',
    risk: '低',
    inputRange: [4000000, 11000000],
    outputRange: [350000, 1100000],
    timeCost: 1,
    cooldown: 1,
    contextLoad: 0.34,
    effect: { test: 2, review: 1, stability: 2 },
    requires: { code: 1 },
    workflowStage: '验证',
    sequenceTip: '先有改动，再跑针对性测试',
    testAction: true,
  },
  {
    id: 'full-suite',
    name: '完整回归',
    command: 'npm run test:all',
    description: '昂贵但扎实；测试越绿，周五晚上越安静。',
    kind: 'verify',
    risk: '低',
    inputRange: [10000000, 24000000],
    outputRange: [750000, 2400000],
    timeCost: 3,
    cooldown: 2,
    contextLoad: 0.48,
    effect: { test: 4, review: 2, stability: 4 },
    requires: { code: 2 },
    workflowStage: '验证',
    sequenceTip: '改动成形后再全量回归',
    testAction: true,
  },
  {
    id: 'self-review',
    name: 'Agent 自审',
    command: '/review --skeptical',
    description: '要求 Agent 假装不认识五分钟前的自己。',
    kind: 'verify',
    risk: '中',
    inputRange: [7000000, 18000000],
    outputRange: [700000, 2100000],
    timeCost: 2,
    cooldown: 2,
    contextLoad: 0.54,
    effect: { test: 2, review: 3, stability: 3 },
    requires: { code: 1, test: 1 },
    workflowStage: '验证',
    sequenceTip: '测试之后让 Agent 挑刺',
  },
  {
    id: 'compress-context',
    name: '压缩上下文',
    command: '/compact',
    description: '把历史总结成一页纸；细节会丢，但窗口能呼吸。',
    kind: 'control',
    risk: '中',
    inputRange: [2500000, 6500000],
    outputRange: [250000, 700000],
    timeCost: 2,
    cooldown: 3,
    contextLoad: 0.12,
    effect: { contextReduction: 0.48, analysis: -1 },
    workflowStage: '控制',
    sequenceTip: '窗口快满时再压缩',
  },
  {
    id: 'git-rollback',
    name: 'Git 回滚',
    command: 'git revert HEAD',
    description: '撤回危险改动，稳定度回来了，进度也回去了。',
    kind: 'control',
    risk: '低',
    inputRange: [1000000, 3000000],
    outputRange: [120000, 320000],
    timeCost: 1,
    cooldown: 3,
    contextLoad: 0.08,
    effect: { code: -2, stability: 14, review: 1 },
    requires: { code: 2 },
    workflowStage: '控制',
    sequenceTip: '出现坏改动后再回滚',
  },
  {
    id: 'search-docs',
    name: '查官方文档',
    command: '/browse --primary-only',
    description: '为版本差异买一份保险，偶尔也会发现文档刚更新。',
    kind: 'inspect',
    risk: '低',
    inputRange: [3000000, 8000000],
    outputRange: [350000, 1000000],
    timeCost: 2,
    cooldown: 2,
    contextLoad: 0.5,
    effect: { analysis: 3, review: 1 },
    requires: { analysis: 1 },
    workflowStage: '调查',
    sequenceTip: '先理解问题，再查版本差异',
  },
]

export const BUFFS: BuffState[] = [
  { id: 'flash-sale', name: '限时六折', description: '接下来 4 次模型调用费用 ×0.6。', icon: '％', discountMultiplier: 0.6, discountUses: 4 },
  { id: 'night-shift', name: '错峰运行', description: '接下来 5 次调用费用 ×0.5，致敬真实低谷价。', icon: '☾', discountMultiplier: 0.5, discountUses: 5 },
  { id: 'cache-whisperer', name: '缓存耳语者', description: '缓存命中比例永久提高 25%。', icon: '⌁', cacheBonus: 0.25 },
  { id: 'prompt-linter', name: '提示词 Linter', description: '本局所有模型可靠性 +8%。', icon: '✓', reliabilityBonus: 0.08 },
  { id: 'elastic-context', name: '弹性上下文', description: '上下文预算上限增加 45K。', icon: '↔', contextBonus: 45000 },
  { id: 'ci-coupon', name: 'CI 体验券', description: '接下来 2 次测试类操作免费。', icon: '▶', testDiscountUses: 2 },
]

export const PROJECTS: ProjectSpec[] = [
  {
    id: 'dark-mode', title: '黑夜里的白色按钮', subtitle: '修复暗色主题回归', client: '像素天气站', kind: 'UI BUG', difficulty: 1, reward: 620,
    brief: '用户切到深色模式后，“保存”按钮仍然亮得像审讯灯。修复颜色变量并保住无障碍对比度。',
    humor: '设计师说这是“极昼主题”，产品经理没有笑。', requirements: { analysis: 2, code: 3, test: 2 }, hiddenRisk: 1,
    file: 'src/components/SaveButton.css', language: 'css',
    codeBefore: `.save-button {\n  color: #17191f;\n  background: #ffffff;\n  border: 1px solid #dfe2e8;\n}`,
    codeAfter: `.save-button {\n  color: var(--button-fg);\n  background: var(--button-bg);\n  border: 1px solid var(--border);\n}`,
    testCommand: 'pnpm test theme --run', failureText: '暗色主题快照仍有 1 处硬编码颜色。', successText: '保存按钮终于不再照亮整个卧室。',
    files: ['src', '  components', '    SaveButton.tsx', '    SaveButton.css', '  styles', '    tokens.css', 'tests', '  theme.spec.ts'],
  },
  {
    id: 'coffee-api', title: '咖啡 API 被薅秃了', subtitle: '加入可靠限流', client: '楼下咖啡机器人', kind: 'BACKEND', difficulty: 2, reward: 780,
    brief: '一位实习生写了 while(true) 请求咖啡，机器已经连续打了 47 杯浓缩。请加入按用户限流。',
    humor: '办公室没有人眨眼，但所有人都在抖。', requirements: { analysis: 3, code: 4, test: 3 }, hiddenRisk: 2,
    file: 'server/routes/brew.ts', language: 'ts',
    codeBefore: `router.post('/brew', async (req, res) => {\n  await machine.brew(req.body);\n  res.send({ ok: true });\n});`,
    codeAfter: `router.post('/brew', rateLimit({\n  windowMs: 60_000, max: 3, key: 'userId'\n}), async (req, res) => {\n  await machine.brew(req.body);\n  res.send({ ok: true });\n});`,
    testCommand: 'vitest run rate-limit', failureText: '并发请求绕过了内存计数器。', successText: '咖啡机恢复理智，实习生开始喝水。',
    files: ['server', '  routes', '    brew.ts', '  middleware', '    rateLimit.ts', 'tests', '  brew.concurrent.test.ts'],
  },
  {
    id: 'todo-offline', title: '待办事项失忆症', subtitle: '补上离线持久化', client: '明天一定做', kind: 'FEATURE', difficulty: 2, reward: 760,
    brief: '刷新页面后所有待办都会消失。客户认为这是“强制清零哲学”，但还是希望数据能保存。',
    humor: '唯一稳定保存下来的，是用户的失望。', requirements: { analysis: 2, code: 4, test: 3 }, hiddenRisk: 2,
    file: 'src/store/tasks.ts', language: 'ts',
    codeBefore: `export const tasks = signal<Task[]>([]);\n\nexport function add(task: Task) {\n  tasks.value = [...tasks.value, task];\n}`,
    codeAfter: `const saved = localStorage.getItem('tasks');\nexport const tasks = signal<Task[]>(saved ? JSON.parse(saved) : []);\n\neffect(() => localStorage.setItem('tasks', JSON.stringify(tasks.value)));`,
    testCommand: 'pnpm test persistence', failureText: '损坏的旧数据导致初始化崩溃。', successText: '刷新之后，拖延仍然忠实地等着用户。',
    files: ['src', '  store', '    tasks.ts', '  views', '    TaskList.tsx', 'tests', '  persistence.spec.ts'],
  },
  {
    id: 'socket-loop', title: 'WebSocket 永动机', subtitle: '终止重连递归', client: '聊天室「还在线吗」', kind: 'INCIDENT', difficulty: 3, reward: 920,
    brief: '断网后客户端每毫秒重连一次，服务器日志像瀑布。加入退避、上限和正确的清理逻辑。',
    humor: '它没有连接上服务器，但连接上了公司的告警系统。', requirements: { analysis: 4, code: 4, test: 4 }, hiddenRisk: 3,
    file: 'src/net/socket.ts', language: 'ts',
    codeBefore: `socket.onclose = () => {\n  connect();\n};`,
    codeAfter: `socket.onclose = () => {\n  if (attempt >= MAX_RETRIES) return;\n  timer = setTimeout(connect, backoff(attempt++));\n};`,
    testCommand: 'vitest run socket.reconnect', failureText: '卸载组件后计时器仍在后台复活。', successText: '告警频道安静下来，SRE 发来了一个句号。',
    files: ['src', '  net', '    socket.ts', '    backoff.ts', 'tests', '  socket.reconnect.test.ts'],
  },
  {
    id: 'invoice-cent', title: '消失的一分钱', subtitle: '修正账单舍入', client: '认真财务有限公司', kind: 'MONEY', difficulty: 3, reward: 980,
    brief: '浮点数让月末账单偶尔少一分钱。改用整数分计价，并迁移旧订单计算。',
    humor: '财务为这一分钱开了一个 63 人会议。', requirements: { analysis: 4, code: 5, test: 4 }, hiddenRisk: 4,
    file: 'src/billing/total.ts', language: 'ts',
    codeBefore: `export const total = (items: Item[]) =>\n  items.reduce((sum, item) => sum + item.price * item.count, 0);`,
    codeAfter: `export const totalCents = (items: Item[]) =>\n  items.reduce((sum, item) => sum + Math.round(item.price * 100) * item.count, 0);`,
    testCommand: 'pnpm test billing --coverage', failureText: '退款路径仍然使用浮点元计算。', successText: '那一分钱回来了，会议却已经预约到下周。',
    files: ['src', '  billing', '    total.ts', '    refund.ts', 'tests', '  currency.property.test.ts'],
  },
  {
    id: 'emoji-sanitizer', title: '评论区表情叛乱', subtitle: '修复 Unicode 截断', client: '猫猫论坛', kind: 'TEXT', difficulty: 2, reward: 820,
    brief: '昵称长度限制会把复合 Emoji 从中间劈开。按字素簇截断，并保留中文昵称。',
    humor: '半个家庭 Emoji 正在考虑向平台提起诉讼。', requirements: { analysis: 3, code: 4, test: 3 }, hiddenRisk: 3,
    file: 'src/text/truncate.ts', language: 'ts',
    codeBefore: `export function shorten(name: string) {\n  return name.slice(0, 12);\n}`,
    codeAfter: `const segmenter = new Intl.Segmenter('zh', { granularity: 'grapheme' });\nexport function shorten(name: string) {\n  return [...segmenter.segment(name)].slice(0, 12).map(x => x.segment).join('');\n}`,
    testCommand: 'vitest run unicode', failureText: '旧版浏览器没有 Intl.Segmenter。', successText: '所有 Emoji 都完整地活了下来。',
    files: ['src', '  text', '    truncate.ts', '    fallback.ts', 'tests', '  unicode.test.ts'],
  },
  {
    id: 'leaderboard-race', title: '排行榜量子态', subtitle: '解决并发覆盖', client: '周末跑分大会', kind: 'DATABASE', difficulty: 4, reward: 1120,
    brief: '两名玩家同时提交分数时，总有一个人的成绩消失。用原子更新修复竞态。',
    humor: '排名第一的人同时也是“查无此人”。', requirements: { analysis: 4, code: 5, test: 5 }, hiddenRisk: 4,
    file: 'api/score.ts', language: 'ts',
    codeBefore: `const board = await db.getBoard();\nboard.push(score);\nawait db.saveBoard(board);`,
    codeAfter: `await db.transaction(async tx => {\n  await tx.scores.upsert({ playerId, score: { max: value } });\n});`,
    testCommand: 'vitest run score.concurrent', failureText: '事务重试没有幂等键，重复写入出现了。', successText: '排行榜坍缩为一个确定的现实。',
    files: ['api', '  score.ts', 'db', '  schema.sql', 'tests', '  score.concurrent.test.ts'],
  },
  {
    id: 'regex-legacy', title: '祖传正则表达式', subtitle: '拆除一行黑魔法', client: '古早会员系统', kind: 'REFACTOR', difficulty: 4, reward: 1180,
    brief: '一条 417 字符的正则负责校验全部用户资料。没有人敢碰，但它开始拒绝合法邮箱。',
    humor: 'Git blame 指向一位已经去山里种茶的前员工。', requirements: { analysis: 5, code: 5, test: 4 }, hiddenRisk: 5,
    file: 'legacy/validate.js', language: 'js',
    codeBefore: `const VALID = /^(?=.{3,64}$)(?!.*[._-]{2})[a-z0-9._-]+@[a-z0-9.-]+\\.[a-z]{2,}$/i;`,
    codeAfter: `export function validateEmail(value) {\n  const at = value.lastIndexOf('@');\n  if (at <= 0) return false;\n  return isLocal(value.slice(0, at)) && isDomain(value.slice(at + 1));\n}`,
    testCommand: 'node --test legacy/*.test.js', failureText: '迁移遗漏了带加号的邮箱地址。', successText: '黑魔法被拆成了三个能看懂的函数。',
    files: ['legacy', '  validate.js', '  validators', '    email.js', 'tests', '  email.cases.json'],
  },
  {
    id: 'cat-sprite', title: '像素猫拒绝落地', subtitle: '修复物理参数', client: '独立游戏工作室', kind: 'GAME', difficulty: 1, reward: 650,
    brief: '像素猫跳起来后飘出了屏幕。修正重力和单位换算，但别让它摔得太惨。',
    humor: '策划坚持说这是开放世界。', requirements: { analysis: 2, code: 3, test: 2 }, hiddenRisk: 1,
    file: 'game/entities/cat.ts', language: 'ts',
    codeBefore: `cat.velocity.y += gravity * delta;\ncat.position.y += cat.velocity.y;`,
    codeAfter: `const seconds = delta / 1000;\ncat.velocity.y += gravity * seconds;\ncat.position.y += cat.velocity.y * seconds;`,
    testCommand: 'pnpm test physics', failureText: '低帧率下猫穿过了地板。', successText: '猫安全落地，并假装一切都在计划之中。',
    files: ['game', '  entities', '    cat.ts', '  physics', '    step.ts', 'tests', '  cat.physics.test.ts'],
  },
  {
    id: 'password-form', title: '密码必须包含月相', subtitle: '简化验证体验', client: '安全但没人能登录', kind: 'UX', difficulty: 2, reward: 800,
    brief: '注册表单要求密码包含大写、小写、数字、符号和“今日月相”。删掉荒谬规则并正确显示强度。',
    humor: '新月时全站注册功能不可用。', requirements: { analysis: 3, code: 4, test: 3 }, hiddenRisk: 2,
    file: 'src/auth/password.ts', language: 'ts',
    codeBefore: `return hasUpper && hasLower && hasDigit && hasSymbol && matchesMoonPhase;`,
    codeAfter: `return {\n  valid: value.length >= 12 && !isCompromised(value),\n  strength: estimateStrength(value)\n};`,
    testCommand: 'pnpm test auth:a11y', failureText: '错误提示没有关联到输入框。', successText: '用户终于不需要打开天文台才能注册。',
    files: ['src', '  auth', '    password.ts', '    breached.ts', 'tests', '  password.a11y.test.ts'],
  },
  {
    id: 'context-leak', title: '客服机器人说漏嘴', subtitle: '隔离租户上下文', client: '云端客服平台', kind: 'SECURITY', difficulty: 5, reward: 1380,
    brief: '客服 Agent 偶尔引用上一家公司的订单。定位缓存键污染并补上租户隔离回归测试。',
    humor: '“猜你喜欢”不应该包含竞争对手的退款单。', requirements: { analysis: 5, code: 5, test: 5 }, hiddenRisk: 6,
    file: 'server/cache/conversation.ts', language: 'ts',
    codeBefore: `const key = 'conversation:' + userId;\nreturn cache.get(key);`,
    codeAfter: `const key = ['conversation', tenantId, userId].map(encodeURIComponent).join(':');\nreturn cache.get(key);`,
    testCommand: 'pnpm test security:isolation', failureText: '后台导出任务仍使用旧缓存键。', successText: '租户边界重新合上，安全群停止刷屏。',
    files: ['server', '  cache', '    conversation.ts', '  jobs', '    export.ts', 'tests', '  tenant-isolation.test.ts'],
  },
  {
    id: 'friday-deploy', title: '周五 17:59 的发布', subtitle: '最终交付', client: '全体老板正在看', kind: 'FINAL BOSS', difficulty: 5, reward: 2200,
    brief: '新版本必须在六点前发布：迁移脚本、支付回调和健康检查同时亮红灯。你听见下班群已经开始发红包。',
    humor: '真正的持续交付，是持续交付你的周末。', requirements: { analysis: 5, code: 6, test: 6 }, hiddenRisk: 7,
    file: 'deploy/release.ts', language: 'ts',
    codeBefore: `await migrate();\nawait deploy();\nawait announce('done');`,
    codeAfter: `await preflight();\nawait deployCanary();\nawait verifyHealth();\nawait promoteOrRollback();`,
    testCommand: 'pnpm run release:dry-run', failureText: '金丝雀实例健康，但支付回调签名失败。', successText: '18:03，发布成功。你错过了红包，但保住了周末。',
    files: ['deploy', '  release.ts', '  canary.ts', '  rollback.ts', 'tests', '  release.dry-run.test.ts'],
  },
]

export const EVENTS: EventSpec[] = [
  {
    id: 'pm-change', eyebrow: '随机事件 · 需求漂移', title: '产品经理发来一句“顺便”', icon: '↝',
    body: '“登录页已经很好了，顺便加一个实时协作白板吧，不复杂。”消息后面跟着一个微笑。',
    choices: [
      { label: '展示工期证据', detail: '消耗一点时间，据理力争。', effect: { time: -2, stability: 5, score: 120 }, result: '你贴出任务拆解。白板进入了“下个版本”，世界暂时恢复秩序。' },
      { label: '说「收到」', detail: '保住时间，代码稳定度承压。', effect: { stability: -12, context: 18000, score: 40 }, result: '需求进入上下文，并迅速繁殖出了三个子需求。' },
    ],
  },
  {
    id: 'pricing-sale', eyebrow: '随机事件 · 计费异动', title: '供应商限时六折', icon: '％',
    body: '控制台弹出一张很小的横幅：未来几次调用享受六折。财务第一次主动给你点赞。',
    choices: [
      { label: '立刻囤调用', detail: '获得“限时六折”Buff。', effect: { buffId: 'flash-sale', score: 80 }, result: '折扣券已进入本局 Buff 栏。便宜不是不用钱，请继续克制。' },
      { label: '保持原计划', detail: '换取少量预算补偿。', effect: { budget: 20, score: 50 }, result: '你关闭横幅，奖励自己一笔“没有冲动消费”的预算。' },
    ],
  },
  {
    id: 'context-ghost', eyebrow: '随机事件 · 上下文污染', title: '幽灵文件回来了', icon: '◌',
    body: '已经删除三个月的 old_final_v7_REAL.ts 突然被 Agent 引用。它对此非常有信心。',
    choices: [
      { label: '清理索引', detail: '释放上下文，但消耗时间。', effect: { context: -32000, time: -2, stability: 4 }, result: '幽灵文件被重新埋葬，至少在下一次缓存恢复之前。' },
      { label: '假装没看见', detail: '节省时间，承担技术债。', effect: { context: 9000, stability: -10 }, result: 'Agent 写下一句“基于现有架构”，所有人都开始紧张。' },
    ],
  },
  {
    id: 'ci-down', eyebrow: '随机事件 · 基础设施', title: 'CI 正在冥想', icon: '∥',
    body: '流水线已经排队 19 分钟，状态页仍然显示“一切正常”。',
    choices: [
      { label: '本地跑测试', detail: '花时间换稳定度。', effect: { time: -3, stability: 9, score: 100 }, result: '风扇起飞了，但关键测试在本地通过。' },
      { label: '相信状态页', detail: '节省时间，押注运气。', effect: { stability: -8, score: 30 }, result: '你获得了一种非常现代的工程体验：不知道。' },
    ],
  },
  {
    id: 'intern-cache', eyebrow: '随机事件 · 意外优化', title: '实习生修好了缓存', icon: '⌁',
    body: '实习生把缓存键多写了一个冒号，结果阴差阳错地解决了碰撞。现在轮到你决定是否保留。',
    choices: [
      { label: '补测试后合并', detail: '获得缓存强化，消耗一点时间。', effect: { time: -2, buffId: 'cache-whisperer', score: 140 }, result: '提交信息写着 fix: lucky colon。缓存命中率确实提高了。' },
      { label: '先回滚再说', detail: '恢复稳定度。', effect: { stability: 10, score: 60 }, result: '幸运冒号离开了主分支，进入公司传说。' },
    ],
  },
  {
    id: 'late-night', eyebrow: '随机事件 · 时区魔法', title: '进入 API 低谷时段', icon: '☾',
    body: '服务器时区与现实生活同时变得模糊。部分供应商的低谷计价开始生效。',
    choices: [
      { label: '开启夜班队列', detail: '未来 5 次调用半价。', effect: { buffId: 'night-shift', time: -1, score: 90 }, result: '任务排入低谷队列。你闻到了凌晨两点的泡面味。' },
      { label: '拒绝熬夜', detail: '恢复稳定度与时间。', effect: { time: 1, stability: 6, score: 70 }, result: '你关掉电脑五分钟，罕见地做出了健康选择。' },
    ],
  },
]

export const HOME_TIPS = [
  'Token 很便宜，直到 Agent 第七次“重新理解整个仓库”。',
  '绿色测试不是装饰品。至少大多数时候不是。',
  '上下文达到 100% 时，最先被遗忘的通常是需求。',
  '最贵的模型也可能自信地修改错误文件。',
]

export function getModel(id: string): ModelSpec {
  return MODELS.find((model) => model.id === id) ?? MODELS[0]
}

export function getProject(id: string): ProjectSpec {
  return PROJECTS.find((project) => project.id === id) ?? PROJECTS[0]
}

export function getCard(id: string): ActionCard {
  return ACTION_CARDS.find((card) => card.id === id) ?? ACTION_CARDS[0]
}
